#### Question 1: Creating a New Column and Filtering a Pandas DataFrame
Description: Using the provided Pandas DataFrame containing the area and population of US states, calculate the population density for each state and add it as a new column to this DataFrame. Then, filter and extract the states with a density greater than 100.

In [6]:
import pandas as pd

In [3]:
states = pd.DataFrame({
    "area": [423967, 695662, 141297, 170312, 149995],
    "pop": [38332521, 26448193, 19651127, 19552860, 12882135]
}, index=["CA", "TX", "NY", "FL", "IL"])

states

      area       pop
CA  423967  38332521
TX  695662  26448193
NY  141297  19651127
FL  170312  19552860
IL  149995  12882135

In [4]:
states["density"] = states["pop"] / states["area"]
states

      area       pop     density
CA  423967  38332521   90.413926
TX  695662  26448193   38.018740
NY  141297  19651127  139.076746
FL  170312  19552860  114.806121
IL  149995  12882135   85.883763

In [ ]:
filtered_states = states[states["density"] > 100] # Filter states with density greater than 100
filtered_states

      area       pop     density
NY  141297  19651127  139.076746
FL  170312  19552860  114.806121