#### Question 3: Structured Array and Row Filtering
Description: Create a Pandas DataFrame from a NumPy structured array with the fields name, age, and weight containing at least 3 members. Then, filter the rows corresponding to individuals older than 25 years.

In [1]:
import pandas as pd
import numpy as np

In [ ]:
dtype = [('name', 'U10'), ('age', 'i4'), ('weight', 'f4')] # Define a structured data type with fields for name, age, and weight
data = np.array([('Zargol', 22, 53), ('Samin', 27, 68.0), ('Bahar', 25, 47), ('Arezo', 29, 75.0)], dtype=dtype)
df = pd.DataFrame(data) # Create a DataFrame from the structured array
df

     name  age  weight
0  Zargol   22    53.0
1   Samin   27    68.0
2   Bahar   25    47.0
3   Arezo   29    75.0

In [6]:
filtered_df = df[df['age'] > 25]  # Filter rows where age is greater than 25
filtered_df

    name  age  weight
1  Samin   27    68.0
3  Arezo   29    75.0