#### Question 4: Shuffling the Rows of a DataFrame
Description: Randomly shuffle the rows of the following DataFrame. (Note: The dimensions have been corrected to $3 \times 3$ to match the 3 specified columns).
df = pd.DataFrame(np.random.rand(3, 10), columns=["A", "B", "C"])

In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.DataFrame(np.random.rand(10, 3), columns=["A", "B", "C"])
df

          A         B         C
0  0.410588  0.002298  0.766289
1  0.824253  0.091591  0.813098
2  0.930651  0.639735  0.886497
3  0.376809  0.915279  0.867802
4  0.632490  0.628390  0.290496
5  0.681372  0.326476  0.960402
6  0.002155  0.631583  0.475663
7  0.772154  0.084717  0.086135
8  0.536913  0.256706  0.219234
9  0.494424  0.217506  0.225248

In [4]:
shuffeled_df = df.sample(frac=1).reset_index(drop=True)  # Shuffle the DataFrame rows
shuffeled_df

          A         B         C
0  0.930651  0.639735  0.886497
1  0.410588  0.002298  0.766289
2  0.494424  0.217506  0.225248
3  0.536913  0.256706  0.219234
4  0.376809  0.915279  0.867802
5  0.772154  0.084717  0.086135
6  0.681372  0.326476  0.960402
7  0.632490  0.628390  0.290496
8  0.824253  0.091591  0.813098
9  0.002155  0.631583  0.475663